version: '3.8'

services:
  # -- PostgreSQL -- ##

  postgres:
    image: postgres:10.7-alpine
    ports:
      - '5444:5432'
    volumes:
      - postgres-data:/var/lib/postgres
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: '${PG_PASS}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_DB: '${PG_DB}'



volumes:
  postgres-data:
  zeebe_data:
  zeebe_elasticsearch_data:
