version: '3.8'

services:


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.12
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      cluster.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m



volumes:
  elasticsearch-data:
